version: '3'

tasks:
  default:
    desc: 'Default task is to "build"'
    deps: [build]

  list:
    desc: 'Lists available tasks'
    cmds:
      - task --list-all

  tidy:
    desc: 'Tidy all'
    cmds:
      - go mod tidy
    sources:
      - '*.go'
      - go.mod
      - go.sum

  build:
    desc: Build the hya-7 binary
    deps: [test]
    cmds:
      - go build -o hya-7 .
    sources:
      - '*.go'
      - go.mod
      - go.sum
    generates:
      - hya-7

  run:
    desc: Run hya-7
    cmds:
      - go run .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: 'Clean all build products'
    cmds:
      - rm -f hya-7
